"""Per-hive MQTT client certificate minting (mTLS).

The broker (`mqtt/mosquitto.conf`) runs with ``require_certificate true`` and
``use_identity_as_username true``: each client authenticates with a TLS client
certificate, and its MQTT username is taken from the certificate's Common Name
(CN). The ACL (`mqtt/acl`) then confines each hive to its own ``hive/<id>/*``
subtree, so a compromised hive cannot touch any other hive's topics.

This module signs short-lived client certs (CN = hive id) with the broker CA so
the controller can hand each hive its own identity at enrollment, replacing the
old single shared username/password. The CA key/cert are generated by
``mqtt/init.sh`` into the ``mqtt_secrets`` volume and mounted (read-only) into the
API container.
"""
from datetime import datetime, timedelta, timezone

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.x509.oid import ExtendedKeyUsageOID, NameOID

from app.core.config import settings

# Client certs are long-lived (the agent reconnects with the same identity across
# restarts); revocation is handled by deleting the hive + future CRL support.
CLIENT_CERT_DAYS = 3650


def _load_ca(
    ca_cert_pem: bytes | None = None, ca_key_pem: bytes | None = None
) -> tuple[x509.Certificate, rsa.RSAPrivateKey]:
    if ca_cert_pem is None:
        with open(settings.mqtt_ca_cert, "rb") as fh:
            ca_cert_pem = fh.read()
    if ca_key_pem is None:
        with open(settings.mqtt_ca_key, "rb") as fh:
            ca_key_pem = fh.read()
    ca_cert = x509.load_pem_x509_certificate(ca_cert_pem)
    ca_key = serialization.load_pem_private_key(ca_key_pem, password=None)
    return ca_cert, ca_key


def issue_client_cert(
    common_name: str,
    *,
    ca_cert_pem: bytes | None = None,
    ca_key_pem: bytes | None = None,
) -> tuple[str, str]:
    """Mint a CA-signed client certificate with the given CN.

    Returns ``(cert_pem, key_pem)`` as strings. The CA material defaults to the
    paths in settings but can be injected (used by tests).
    """
    ca_cert, ca_key = _load_ca(ca_cert_pem, ca_key_pem)

    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    subject = x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, common_name)])
    now = datetime.now(timezone.utc)
    cert = (
        x509.CertificateBuilder()
        .subject_name(subject)
        .issuer_name(ca_cert.subject)
        .public_key(key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(now - timedelta(minutes=5))
        .not_valid_after(now + timedelta(days=CLIENT_CERT_DAYS))
        .add_extension(x509.BasicConstraints(ca=False, path_length=None), critical=True)
        .add_extension(
            x509.ExtendedKeyUsage([ExtendedKeyUsageOID.CLIENT_AUTH]), critical=False
        )
        .sign(ca_key, hashes.SHA256())
    )

    cert_pem = cert.public_bytes(serialization.Encoding.PEM).decode("utf-8")
    key_pem = key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.TraditionalOpenSSL,
        encryption_algorithm=serialization.NoEncryption(),
    ).decode("utf-8")
    return cert_pem, key_pem
